services:
  - type: web
    name: kklijp
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
      - key: KKLIJP_ADMIN_PASSWORD
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PGSSL
        value: "true"
