import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, UploadCloud, Heart, Eye, MessageCircle, Flame, X, Grid2X2, List, Zap, Link as LinkIcon, User, Play, ExternalLink, ShieldCheck, Trash2, Save, CheckCircle2, Clock3, Share2, Copy } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8787';
const fallbackCats = [{id:'all',label:'Alles',count:0},{id:'painful',label:'Pijnlijk',count:0},{id:'risky',label:'Riskant',count:0},{id:'inventive',label:'Uitvindingen',count:0},{id:'games',label:'Games',count:0},{id:'lifehacks',label:'Lifehacks',count:0},{id:'skills',label:'Vaardigheden',count:0},{id:'hotties',label:'Hotties',count:0},{id:'wtf',label:'WTF',count:0},{id:'fails',label:'Fails',count:0},{id:'random',label:'Willekeurig',count:0}];
function fmt(n=0){ if(n>=1e6)return`${(n/1e6).toFixed(1)}M`; if(n>=1e3)return`${(n/1e3).toFixed(1)}K`; return String(n||0); }
function ago(iso){ const s=Math.max(1,Math.floor((Date.now()-new Date(iso).getTime())/1000)); if(s<60)return`${s}s geleden`; const m=Math.floor(s/60); if(m<60)return`${m}m geleden`; const h=Math.floor(m/60); if(h<24)return`${h}u geleden`; return`${Math.floor(h/24)}d geleden`; }
async function api(path,opt={}){ const r=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt}); const d=await r.json().catch(()=>null); if(!r.ok)throw new Error(d?.error||'API fout'); return d; }
function Logo(){ return <div className="logo"><div className="dead">×_×</div><div className="word"><span>KK</span>LIJP</div></div> }
function statusLabel(status){ return status==='approved'?'Goedgekeurd':status==='pending'?'Wachtend':'Onbekend'; }

function App(){
  const [videos,setVideos]=useState([]),[top,setTop]=useState([]),[cats,setCats]=useState(fallbackCats);
  const [category,setCategory]=useState('all'),[query,setQuery]=useState(''),[sort,setSort]=useState('date'),[order,setOrder]=useState('desc'),[layout,setLayout]=useState('grid');
  const [post,setPost]=useState(false),[active,setActive]=useState(null),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true);
  const [username,setUsername]=useState(localStorage.getItem('kklijp_username')||'');
  async function load(){ setLoading(true); const qs=new URLSearchParams({q:query,category,sort,order}); const [v,t,c]=await Promise.all([api(`/api/videos?${qs}`),api('/api/top'),api('/api/categories')]); setVideos(v); setTop(t); setCats(c); setLoading(false); }
  useEffect(()=>{ const id=setTimeout(load,180); return()=>clearTimeout(id); },[query,category,sort,order]);
  useEffect(()=>{ const id=new URLSearchParams(location.search).get('v'); if(id) api(`/api/videos/${id}`).then(setActive).catch(()=>{}); },[]);
  return <div className="app"><div className="orb a"/><div className="orb b"/><div className="gridBg"/>
    <Header query={query} setQuery={setQuery} onPost={()=>setPost(true)} username={username} setUsername={setUsername} admin={admin} setAdmin={setAdmin}/>
    {admin?<AdminPanel/>:<main className="container"><CategoryNav cats={cats} category={category} setCategory={setCategory}/><div className="content"><section className="feed"><div className="feedHead"><h2><Zap size={18}/> {category==='all'?"Nieuwste video's":`${cats.find(c=>c.id===category)?.label || category} video's`}</h2><div className="controls"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Datum</option><option value="likes">Likes</option><option value="views">Weergaven</option><option value="name">Titel</option></select><button className="chip" onClick={()=>setOrder(order==='desc'?'asc':'desc')}>{order==='desc'?'Aflopend':'Oplopend'}</button><button className={layout==='grid'?'icon active':'icon'} onClick={()=>setLayout('grid')}><Grid2X2 size={18}/></button><button className={layout==='list'?'icon active':'icon'} onClick={()=>setLayout('list')}><List size={18}/></button></div></div>{loading?<div className="empty">Laden...</div>:videos.length?<div className={layout==='grid'?'videoGrid':'videoList'}>{videos.map(v=><VideoCard key={v.id} video={v} layout={layout} open={()=>setActive(v)} load={load} username={username} setUsername={setUsername}/>)}</div>:<div className="empty">Geen video's gevonden.</div>}</section><aside><Sidebar top={top} open={setActive}/></aside></div></main>}
    <Footer/>
    <AnimatePresence>{post&&<PostModal onClose={()=>setPost(false)} refresh={load} username={username} setUsername={setUsername}/>} {active&&<VideoModal video={active} close={()=>setActive(null)} refresh={load} username={username} setUsername={setUsername}/>}</AnimatePresence>
  </div>
}
function Header(p){ return <header className="top"><div className="topInner"><button className="brand" onClick={()=>location.href='/'}><Logo/><small className="versionBadge">v1.4</small></button><div className="search"><Search size={19}/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Zoek video’s, hashtags, categorieën, plaatser..."/></div><NameBox username={p.username} setUsername={p.setUsername}/><button className="upload" onClick={p.onPost}><UploadCloud size={18}/> Video plaatsen</button><button className="admin" onClick={()=>p.setAdmin(!p.admin)}><ShieldCheck size={18}/></button></div></header> }
function NameBox({username,setUsername}){ const [open,setOpen]=useState(false),[name,setName]=useState(username),[err,setErr]=useState(''); async function save(){ try{ const r=await api('/api/session',{method:'POST',body:JSON.stringify({name})}); localStorage.setItem('kklijp_username',r.username); setUsername(r.username); setOpen(false); setErr(''); }catch(e){setErr(e.message)} } return <div className="nameBox"><button className={username?'nameBtn':'nameBtn warn'} onClick={()=>setOpen(!open)}><User size={16}/>{username||'Naam'}</button>{open&&<div className="namePop"><b>Jouw naam</b><p>Deze naam wordt gekoppeld aan jouw IP-adres.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Naam"/><button onClick={save}>Opslaan</button>{err&&<small>{err}</small>}</div>}</div> }
function CategoryNav({cats,category,setCategory}){ return <nav className="catNav">{cats.map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={category===c.id?'active':''}>{c.label} <span>({c.count})</span></button>)}</nav> }
function VideoCard({video,layout,open,load,username,setUsername}){ const tags=(video.hashtags||[]).slice(0,4),extra=Math.max(0,(video.hashtags||[]).length-tags.length); async function like(e){ e.stopPropagation(); const name=username||prompt('Welke naam gebruik je?'); if(!name)return; try{ await api(`/api/videos/${video.id}/like`,{method:'POST',body:JSON.stringify({name})}); localStorage.setItem('kklijp_username',name); setUsername(name); load(); }catch(err){alert(err.message)} } return <motion.article layout className={layout==='list'?'card list':'card'} onClick={open} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div className="thumb">{video.thumbnailUrl?<img src={video.thumbnailUrl}/>:<div className="noThumb">Geen thumbnail</div>}<div className="play"><Play fill="currentColor"/></div></div><div className="body"><h3>{video.title}</h3><p><b>{video.postedBy}</b> · {ago(video.createdAt)}</p><div className="stats"><button onClick={like}><Heart size={16}/> {fmt(video.likes)}</button><span><Eye size={16}/> {fmt(video.views)}</span><span><MessageCircle size={16}/> {(video.comments||[]).length}</span></div><div className="tags">{tags.map(t=><span key={t}>#{t}</span>)}{extra>0&&<span>+{extra}</span>}</div></div></motion.article> }
function Sidebar({top,open}){ return <><div className="side"><h3><Flame size={17}/> Lijpste video's</h3>{top.map((v,i)=><button className="topRow" key={v.id} onClick={()=>open(v)}><strong>{i+1}</strong>{v.thumbnailUrl&&<img src={v.thumbnailUrl}/>}<span>{v.title}<small><Eye size={12}/> {fmt(v.views)} · <Heart size={12}/> {fmt(v.likes)}</small></span></button>)}</div><div className="promo"><Logo/><p>RAUW. SNEL. LIJP.</p><small>Upload. Kijk. Deel.</small></div></> }
function PostModal({onClose,refresh,username,setUsername}){ const [form,setForm]=useState({name:username,url:'',title:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false); async function submit(e){ e.preventDefault(); setBusy(true); setErr(''); try{ const v=await api('/api/videos',{method:'POST',body:JSON.stringify(form)}); localStorage.setItem('kklijp_username',v.postedBy); setUsername(v.postedBy); alert('Video staat in de wachtrij. Admin moet hem accepteren.'); refresh(); onClose(); }catch(e){setErr(e.message)}finally{setBusy(false)} } return <motion.div className="backdrop"><form className="modal post" onSubmit={submit}><button type="button" className="close" onClick={onClose}><X/></button><h2>Video plaatsen</h2><p>Iedereen kan plaatsen. Nieuwe video’s komen eerst in de admin-wachtrij.</p><label><User size={18}/><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Jouw naam"/></label><label><LinkIcon size={18}/><input required value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="YouTube / Shorts / Facebook link"/></label><label><Zap size={18}/><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Eigen titel"/></label>{err&&<div className="error">{err}</div>}<button className="submit" disabled={busy}>{busy?'Bezig...':'Zet in wachtrij'}</button><small>Flood protection actief: max 3 uploads per 10 minuten.</small></form></motion.div> }
function VideoModal({video,close,refresh,username,setUsername}){ const [cur,setCur]=useState(video),[comment,setComment]=useState(''),[err,setErr]=useState(''); const shareUrl=useMemo(()=>`${location.origin}${location.pathname}?v=${cur.id}`,[cur.id]); useEffect(()=>{ api(`/api/videos/${video.id}/view`,{method:'POST'}).then(v=>{setCur(v); refresh();}).catch(()=>{}); },[video.id]); async function addComment(e){ e.preventDefault(); const name=username||prompt('Welke naam gebruik je?'); if(!name)return; try{ const v=await api(`/api/videos/${cur.id}/comments`,{method:'POST',body:JSON.stringify({name,text:comment})}); localStorage.setItem('kklijp_username',name); setUsername(name); setCur(v); setComment(''); setErr(''); }catch(e){setErr(e.message)} } async function share(){ if(navigator.share) await navigator.share({title:cur.title,url:shareUrl}).catch(()=>{}); else { await navigator.clipboard.writeText(shareUrl); alert('KKLIJP-link gekopieerd.'); } } return <motion.div className="backdrop"><div className="modal watch"><button className="close" onClick={close}><X/></button><div className="player"><iframe src={cur.embedUrl} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><div className="watchInfo"><h2>{cur.title}</h2><p><b>{cur.postedBy}</b> · {fallbackCats.find(c=>c.id===cur.category)?.label || cur.category} · {ago(cur.createdAt)}</p><div className="shareBox"><button onClick={share}><Share2 size={17}/> Deel</button><input readOnly value={shareUrl}/><button onClick={()=>navigator.clipboard.writeText(shareUrl)}><Copy size={17}/></button></div><div className="tags allTags">{(cur.hashtags||[]).map(t=><span key={t}>#{t}</span>)}</div><a className="original" href={cur.url} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Originele link</a><section><h3>Reacties</h3><form className="commentForm" onSubmit={addComment}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={username?`Reageer als ${username}`:'Reageer met jouw naam'}/><button>Reageer</button></form>{err&&<small className="errText">{err}</small>}{(cur.comments||[]).map(c=><div className="comment" key={c.id}><b>{c.name}</b><span>{ago(c.createdAt)}</span><p>{c.text}</p></div>)}</section></div></div></motion.div> }
function AdminPanel(){ const [password,setPassword]=useState(localStorage.getItem('kklijp_admin')||''),[rows,setRows]=useState([]),[status,setStatus]=useState('pending'),[err,setErr]=useState(''); const headers={'x-admin-password':password}; async function load(){ try{ setRows(await api(`/api/admin/videos?status=${status}`,{headers})); localStorage.setItem('kklijp_admin',password); setErr(''); }catch(e){setErr(e.message)} } useEffect(()=>{ if(password)load(); },[status]); async function approve(id){ await api(`/api/admin/videos/${id}/approve`,{method:'POST',headers}); load(); } async function del(id){ if(confirm('Verwijderen?')){ await api(`/api/admin/videos/${id}`,{method:'DELETE',headers}); load(); } } async function save(v){ await api(`/api/admin/videos/${v.id}`,{method:'PATCH',headers,body:JSON.stringify(v)}); load(); } return <main className="container adminWrap"><div className="adminHead"><h2><ShieldCheck/> Adminpaneel</h2><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Adminwachtwoord"/><button onClick={load}>Openen</button></div>{err&&<div className="error">{err}</div>}<div className="catNav"><button className={status==='pending'?'active':''} onClick={()=>setStatus('pending')}>Wachtend</button><button className={status==='approved'?'active':''} onClick={()=>setStatus('approved')}>Goedgekeurd</button><button className={status==='all'?'active':''} onClick={()=>setStatus('all')}>Alles</button></div><div className="adminList">{rows.map(v=><AdminVideo key={v.id} video={v} approve={()=>approve(v.id)} del={()=>del(v.id)} save={save}/>)}</div></main> }
function AdminVideo({video,approve,del,save}){ const [v,setV]=useState({...video,hashtags:(video.hashtags||[]).join(' ')}); return <div className="adminVideo"><div className="adminThumb">{video.thumbnailUrl?<img src={video.thumbnailUrl}/>:<Play/>}<span>{statusLabel(video.status)}</span></div><div className="adminFields"><input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/><select value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{fallbackCats.filter(c=>c.id!=='all').map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><textarea value={v.hashtags} onChange={e=>setV({...v,hashtags:e.target.value})}/><small>Geplaatst door {video.postedBy} · {video.platform}</small><div><button onClick={()=>save(v)}><Save size={16}/>Opslaan</button>{video.status!=='approved'&&<button onClick={approve}><CheckCircle2 size={16}/>Accepteren</button>}<button className="danger" onClick={del}><Trash2 size={16}/>Verwijderen</button></div></div></div> }
function Footer(){ return <footer><Logo/><span>Over</span><span>Regels</span><span>Privacy</span><span>Contact</span><em>© 2026 KKLIJP</em></footer> }
createRoot(document.getElementById('root')).render(<App/>);
