import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API = '';
const baseCats = [
  ['all','Alles'],['reels','Reels'],['painful','Pijnlijk'],['risky','Riskant'],['inventive','Uitvindingen'],['games','Games'],['lifehacks','Lifehacks'],['skills','Skills'],['hotties','Hotties'],['wtf','WTF'],['fails','Fails'],['random','Random']
].map(([id,label])=>({id,label,count:0}));
const fmt=n=>n>=1000?(n/1000).toFixed(1)+'K':String(n||0);
const ago=iso=>{let s=Math.max(1,((Date.now()-new Date(iso).getTime())/1000)|0); if(s<60)return s+'s geleden'; let m=(s/60)|0; if(m<60)return m+'m geleden'; let h=(m/60)|0; if(h<24)return h+'u geleden'; return ((h/24)|0)+'d geleden'};
async function api(path,opt={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'API fout');return d}
function Logo(){return <button className="brand" onClick={()=>location.href='/'}><span className="dead">×_×</span><span className="word"><b>KK</b>LIJP</span><small>v2</small></button>}
function App(){
 const [page,setPage]=useState(location.pathname.startsWith('/reels')?'reels':location.pathname.startsWith('/admin')?'admin':'videos');
 const [videos,setVideos]=useState([]),[reels,setReels]=useState([]),[topV,setTopV]=useState([]),[topR,setTopR]=useState([]),[cats,setCats]=useState(baseCats),[active,setActive]=useState(null);
 const [q,setQ]=useState(''),[cat,setCat]=useState('all'),[sort,setSort]=useState('date'),[order,setOrder]=useState('desc'),[post,setPost]=useState(false),[user,setUser]=useState(localStorage.getItem('kklijp_username')||'');
 async function load(){const qs=new URLSearchParams({q,category:cat,sort,order,type:page==='reels'?'reel':'video'}); const [v,c,tv,tr]=await Promise.all([api('/api/videos?'+qs),api('/api/categories'),api('/api/top?type=video'),api('/api/top?type=reel')]); setVideos(v); setReels(v); setCats(c); setTopV(tv); setTopR(tr)}
 useEffect(()=>{const t=setTimeout(load,150);return()=>clearTimeout(t)},[q,cat,sort,order,page]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('v'); if(id) api('/api/videos/'+id).then(setActive).catch(()=>{})},[]);
 function nav(p){history.pushState(null,'',p==='reels'?'/reels':p==='admin'?'/admin':'/');setPage(p)}
 return <div className="app"><Header page={page} nav={nav} q={q} setQ={setQ} user={user} setUser={setUser} openPost={()=>setPost(true)}/>{page==='admin'?<Admin/>:page==='reels'?<ReelsPage reels={reels} setActive={setActive} user={user} setUser={setUser} reload={load}/>:<Home videos={videos} cats={cats} cat={cat} setCat={setCat} sort={sort} setSort={setSort} order={order} setOrder={setOrder} setActive={setActive} topV={topV} topR={topR} user={user} setUser={setUser} reload={load}/>}<Footer/>{post&&<PostModal close={()=>setPost(false)} user={user} setUser={setUser} reload={load}/>} {active&&<VideoModal video={active} close={()=>setActive(null)} reload={load} user={user} setUser={setUser}/>}</div>
}
function Header({page,nav,q,setQ,user,setUser,openPost}){return <header className="top"><div className="topInner"><Logo/><button className={page==='videos'?'tab active':'tab'} onClick={()=>nav('videos')}>Video's</button><button className={page==='reels'?'tab active':'tab'} onClick={()=>nav('reels')}>Reels</button><div className="search">🔎<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Zoek titel, tags, categorie of naam..."/></div><NameBox user={user} setUser={setUser}/><button className="upload" onClick={openPost}>+ Video plaatsen</button><button className={page==='admin'?'tab active':'tab'} onClick={()=>nav('admin')}>Admin</button></div></header>}
function NameBox({user,setUser}){const [open,setOpen]=useState(false),[name,setName]=useState(user),[err,setErr]=useState(''); async function save(){try{const r=await api('/api/session',{method:'POST',body:JSON.stringify({name})});localStorage.setItem('kklijp_username',r.username);setUser(r.username);setOpen(false)}catch(e){setErr(e.message)}} return <div className="nameBox"><button className="tab" onClick={()=>setOpen(!open)}>{user||'Naam'}</button>{open&&<div className="namePop"><b>Jouw naam</b><p>Wordt gekoppeld aan jouw IP.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Naam"/><button onClick={save}>Opslaan</button>{err&&<small>{err}</small>}</div>}</div>}
function Home(p){return <main className="container"><nav className="catNav">{p.cats.map(c=><button key={c.id} className={p.cat===c.id?'active':''} onClick={()=>p.setCat(c.id)}>{c.label} ({c.count})</button>)}</nav><div className="content"><section><div className="feedHead"><h2>{p.cat==='all'?'Nieuwste video’s':(p.cats.find(c=>c.id===p.cat)?.label||p.cat)}</h2><div className="controls"><select value={p.sort} onChange={e=>p.setSort(e.target.value)}><option value="date">Datum</option><option value="likes">Likes</option><option value="views">Weergaven</option><option value="name">Titel</option></select><button className="chip" onClick={()=>p.setOrder(p.order==='desc'?'asc':'desc')}>{p.order==='desc'?'Aflopend':'Oplopend'}</button></div></div><div className="videoGrid">{p.videos.length?p.videos.map(v=><VideoCard key={v.id} v={v} open={()=>p.setActive(v)} user={p.user} setUser={p.setUser} reload={p.reload}/>):<div className="empty">Geen video’s gevonden.</div>}</div></section><Sidebar topV={p.topV} topR={p.topR} open={p.setActive}/></div></main>}
function Sidebar({topV,topR,open}){return <aside><TopList title="Lijpste video's" rows={topV} open={open}/><TopList title="Lijpste reels" rows={topR} open={open}/></aside>}
function TopList({title,rows,open}){return <div className="side"><h3>🔥 {title}</h3>{rows.map((v,i)=><button className="topRow" key={v.id} onClick={()=>open(v)}><b>{i+1}</b>{v.thumbnailUrl&&<img src={v.thumbnailUrl}/>}<span>{v.title}<small>👁 {fmt(v.views)} · ❤ {fmt(v.likes)}</small></span></button>)}</div>}
function VideoCard({v,open,user,setUser,reload}){const tags=(v.hashtags||[]).slice(0,4);async function like(e){e.stopPropagation();const name=user||prompt('Naam?');if(!name)return;try{await api('/api/videos/'+v.id+'/like',{method:'POST',body:JSON.stringify({name})});localStorage.setItem('kklijp_username',name);setUser(name);reload()}catch(err){alert(err.message)}}return <article className="card" onClick={open}><div className="thumb">{v.thumbnailUrl?<img src={v.thumbnailUrl}/>:<div className="noThumb">Geen thumbnail</div>}<div className="play">▶</div>{v.type==='reel'&&<span className="badge">REEL</span>}</div><div className="body"><h3>{v.title}</h3><p><b>{v.postedBy}</b> · {ago(v.createdAt)}</p><div className="stats"><button onClick={like}>❤ {fmt(v.likes)}</button><span>👁 {fmt(v.views)}</span><span>💬 {(v.comments||[]).length}</span></div><div className="tags">{tags.map(t=><span key={t}>#{t}</span>)}</div></div></article>}
function ReelsPage({reels,setActive,user,setUser,reload}){return <main className="reelsPage"><div className="reelsFeed">{reels.length?reels.map(v=><ReelCard key={v.id} v={v} open={()=>setActive(v)} user={user} setUser={setUser} reload={reload}/>):<div className="empty reelsEmpty">Geen reels gevonden.</div>}</div></main>}
function ReelCard({v,open,user,setUser,reload}){async function like(e){e.stopPropagation();const name=user||prompt('Naam?');if(!name)return;try{await api('/api/videos/'+v.id+'/like',{method:'POST',body:JSON.stringify({name})});localStorage.setItem('kklijp_username',name);setUser(name);reload()}catch(err){alert(err.message)}}return <section className="reelCard"><div className="reelPlayer" onClick={open}><iframe src={v.embedUrl} allow="autoplay; encrypted-media; picture-in-picture; web-share" allowFullScreen/></div><div className="reelInfo"><h2>{v.title}</h2><p>@{v.postedBy}</p><div><button onClick={like}>❤ {fmt(v.likes)}</button><button onClick={open}>💬 {(v.comments||[]).length}</button><button onClick={()=>navigator.clipboard.writeText(location.origin+'/?v='+v.id)}>Delen</button></div></div></section>}
function PostModal({close,user,setUser,reload}){const [f,setF]=useState({name:user,url:'',title:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{const v=await api('/api/videos',{method:'POST',body:JSON.stringify(f)});localStorage.setItem('kklijp_username',v.postedBy);setUser(v.postedBy);alert('Video staat in de wachtrij.');reload();close()}catch(e){setErr(e.message)}finally{setBusy(false)}}return <div className="backdrop"><form className="modal post" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><h2>Video plaatsen</h2><p>Nieuwe video’s/reels komen eerst in de admin-wachtrij.</p><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Jouw naam"/><input required value={f.url} onChange={e=>setF({...f,url:e.target.value})} placeholder="YouTube, Shorts of Facebook link"/><input value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Eigen titel"/>{err&&<div className="error">{err}</div>}<button className="submit" disabled={busy}>{busy?'Bezig...':'Zet in wachtrij'}</button></form></div>}
function VideoModal({video,close,reload,user,setUser}){const [cur,setCur]=useState(video),[comment,setComment]=useState(''),[err,setErr]=useState('');const share=location.origin+'/?v='+cur.id;useEffect(()=>{api('/api/videos/'+video.id+'/view',{method:'POST'}).then(v=>{setCur(v);reload()}).catch(()=>{})},[video.id]);async function add(e){e.preventDefault();const name=user||prompt('Naam?');if(!name)return;try{const v=await api('/api/videos/'+cur.id+'/comments',{method:'POST',body:JSON.stringify({name,text:comment})});localStorage.setItem('kklijp_username',name);setUser(name);setCur(v);setComment('')}catch(e){setErr(e.message)}}return <div className="backdrop"><div className="modal watch"><button className="close" onClick={close}>×</button><div className={cur.type==='reel'?'player reelModal':'player'}><iframe src={cur.embedUrl} allow="autoplay; encrypted-media; picture-in-picture; web-share" allowFullScreen/></div><div className="watchInfo"><h2>{cur.title}</h2><p><b>{cur.postedBy}</b> · {cur.type==='reel'?'Reel':'Video'} · {ago(cur.createdAt)}</p><div className="shareBox"><button onClick={()=>navigator.clipboard.writeText(share)}>Kopieer deel-link</button><input readOnly value={share}/></div><div className="tags allTags">{(cur.hashtags||[]).map(t=><span key={t}>#{t}</span>)}</div><a className="original" href={cur.url} target="_blank">Originele link</a><section><h3>Reacties</h3><form className="commentForm" onSubmit={add}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={user?'Reageer als '+user:'Reageer met jouw naam'}/><button>Reageer</button></form>{err&&<small className="errText">{err}</small>}{(cur.comments||[]).map(c=><div className="comment" key={c.id}><b>{c.name}</b><span>{ago(c.createdAt)}</span><p>{c.text}</p></div>)}</section></div></div></div>}
function Admin(){const [pass,setPass]=useState(localStorage.getItem('kklijp_admin')||''),[ok,setOk]=useState(false),[rows,setRows]=useState([]),[status,setStatus]=useState('pending'),[batch,setBatch]=useState(''),[err,setErr]=useState('');const headers={'x-admin-password':pass};async function login(){try{await api('/api/admin/check',{method:'POST',headers});localStorage.setItem('kklijp_admin',pass);setOk(true);load()}catch(e){setErr(e.message)}}async function load(){const r=await api('/api/admin/videos?status='+status,{headers});setRows(r)}useEffect(()=>{if(ok)load()},[status,ok]);async function approve(id){await api('/api/admin/videos/'+id+'/approve',{method:'POST',headers});load()}async function del(id){if(confirm('Verwijderen?')){await api('/api/admin/videos/'+id,{method:'DELETE',headers});load()}}async function save(v){await api('/api/admin/videos/'+v.id,{method:'PATCH',headers,body:JSON.stringify(v)});load()}async function importBatch(){try{const r=await api('/api/admin/batch',{method:'POST',headers,body:JSON.stringify({text:batch})});alert(r.added+' video’s toegevoegd aan wachtrij.');setBatch('');load()}catch(e){alert(e.message)}}if(!ok)return <main className="container adminLogin"><h1>Adminpaneel</h1><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Admin wachtwoord"/><button className="submit" onClick={login}>Inloggen</button>{err&&<div className="error">{err}</div>}</main>;return <main className="container adminWrap"><div className="adminStatus">INGELOGD ALS ADMIN</div><div className="catNav"><button className={status==='pending'?'active':''} onClick={()=>setStatus('pending')}>Wachtend</button><button className={status==='approved'?'active':''} onClick={()=>setStatus('approved')}>Goedgekeurd</button><button className={status==='all'?'active':''} onClick={()=>setStatus('all')}>Alles</button></div><section className="batch"><h3>Batch import</h3><p>Formaat: link | titel | naam. Max 200 regels.</p><textarea value={batch} onChange={e=>setBatch(e.target.value)} placeholder="https://... | Titel | naam"/><button onClick={importBatch}>Importeer batch</button></section><div className="adminList">{rows.map(v=><AdminVideo key={v.id} video={v} approve={()=>approve(v.id)} del={()=>del(v.id)} save={save}/>)}</div></main>}
function AdminVideo({video,approve,del,save}){const [v,setV]=useState({...video,hashtags:(video.hashtags||[]).join(' ')});return <div className="adminVideo"><div className={video.type==='reel'?'adminThumb reelThumb':'adminThumb'}>{video.thumbnailUrl?<img src={video.thumbnailUrl}/>:<span>Geen thumbnail</span>}<em>{video.status} · {video.type}</em></div><div className="adminFields"><input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/><input value={v.postedBy} onChange={e=>setV({...v,postedBy:e.target.value})}/><select value={v.type} onChange={e=>setV({...v,type:e.target.value})}><option value="video">video</option><option value="reel">reel</option></select><select value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{baseCats.filter(c=>!['all','reels'].includes(c.id)).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><textarea value={v.hashtags} onChange={e=>setV({...v,hashtags:e.target.value})}/><input value={v.thumbnailUrl||''} onChange={e=>setV({...v,thumbnailUrl:e.target.value})} placeholder="Thumbnail"/><input value={v.url} onChange={e=>setV({...v,url:e.target.value})}/><div><button onClick={()=>save(v)}>Bewerken</button>{video.status!=='approved'&&<button onClick={approve}>Accepteren</button>}<button className="danger" onClick={del}>Verwijderen</button></div></div></div>}
function Footer(){return <footer><span>×_× KKLIJP</span><em>Video's en reels voor de vriendengroep.</em></footer>}
createRoot(document.getElementById('root')).render(<App/>);
